AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation workshop - Template and stack (uksb-1q9p31idr).

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: stack-dependencies
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: stack-dependencies
        - Key: Usage
          Value: 'Put main stack dependencies'
        - Key: Date
          Value: '2023-03-21'
